### ISSUE TITLE
Feature Request: Missing Merit Tracking

### ISSUE THREAD

**Issue by jgonyea** [Mephiles/torntools_extension#1]
There are a few merits surrounding various areas not tracked by TT in the left sidebar:

- https://www.torn.com/church.php (donations, marriage, etc)

- https://www.torn.com/properties.php (building of an airstrip, yacht, etc)

**Comment by Mephiles** [comment]
Marriage is displayed under Home page right now. I don't want to segregate too much. (Adding marriage under church is (in my opinion) not a good idea as people don't visit church that much (I think?))

Donations aren't tracked because I have done achievements based on personal stats provided by Torn's API. I will add it in the next update (I just checked and I can get the stat from the page itself).

When it comes to building an airstrip or owning a yacht, I don't want to add achievements that are for one single item or action (i.e. building an airstrip) but rather achievements like "do x crimes" because displaying them in the menu makes it easier for the player to keep track of such achievements. Adding all achievements to the menu would clutter it too much.

**Comment by jgonyea** [comment]
All that makes sense. Thanks!
