### ISSUE TITLE
Auto buy feature

### ISSUE THREAD

**Issue by AmploDev** [Mephiles/torntools_extension#687]
I have created a feature to auto buy items in Bit's 'n Bobs. I made it a seperate feature, but this could extend the Shop auto fill feature. Now instead of only the Fill max button you also get a Buy max button.

Pressing the button fills in the max amount (same method as the Shops auto fill feature) and then auto buys them by clicking the Buy button and the confirm button. So it saves you 2 clicks (usefull when buying beer).

I have added a few settings:
 - Bit's and Bobs - Show buy max button. (checkbox, default on)
   - Ignore cash on hand for buy max button. (checkbox, default off)
   - Autoconfirm. (checkbox, default on)

The rules of Torn are:
If the software you're using makes non-API requests that are not manually triggered by you, it is not allowed and can be tracked.

Is this an allowed feature? You are manually clicking the Buy max button, but the actual Confirm click is done by the script. I could remove the autoconfirm feature, so you manually have to press confirm. 

So should I do a pull request or is this a useless effort.

**Comment by DeKleineKobini** [comment]
Sorry, completely missed this one due to personal reasons. 

Rules wise this is a gray area, so I'd need explicit permission by IBF to consider it.

Besides the legality, I'm not sure how useful it actually would be. Fill max is already fairly close in functionality. And I can't imagine it being that much faster, and the speed is probably not needed either. I'll assign it to another contributor for his opinion though.

**Comment by AmploDev** [comment]
Hello,

I have stopped playing the game entirely so think you can also just close this request.

**Comment by DeKleineKobini** [comment]
Then I indeed will do so.
