### ISSUE TITLE
Company capacity special not recognized in abroad auto fill

### ISSUE THREAD

**Issue by sxe** [Mephiles/torntools_extension#755]
Hi, 
I just got the company special that gives 5 extra travel capacity (flower shop). 
This shows correctly (34 capacity for me) at the "Choose destination" page before you start the flight.

When landing, it doesn't fill in the correct capacity. It still fills 29. When I bought 29, it showed -1. I could then manually change the value to 5 and buy 5 more. 

The fact that it shows the correct value before the flight tells me it is possible to get the correct value from the api.
I only tested it abroad in Africa, so I am not sure if it's a problem with "African Violet" or a general problem.

If you need more info I can get it in a couple hours when I am abroad again

Cheers.

**Comment by Sashank999** [comment]
Whenever you raise an issue in Github, we expect you to also say your in-game name and ID so we can contact you faster rather than waiting for your reply on Github issues.

The Abroad Auto Fill considers the maximum limit shown on the page. Maybe it was shown incorrectly ? I prefer screenshots. It would be better if you include a screenshot next time you landed abroad.

**Comment by sxe** [comment]
ok sure thanks. I will add the missing information next time I am abroad.

**Comment by Sashank999** [comment]
What is your in-game ID ?

**Comment by sxe** [comment]
Aarden [2871679]

**Comment by Sashank999** [comment]
Fixed in 521de6cea5cdc61adabe9cea263546227e6554ec .
